channels:
- conda-forge
dependencies:
- python=3.9.15
- pip<=23.2.1
- pip:
  - mlflow==2.5.0
  - cloudpickle==2.2.1
  - nltk==3.8.1
  - numpy==1.25.1
  - psutil==5.9.5
  - regex==2023.6.3
  - scikit-learn==1.3.0
  - scipy==1.11.1
name: mlflow-env
